before_script:    
  - echo "Hoping this won't break anything"
  
cooking:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "beta"

  tags:
    - polestar
  script:
    - cd /home/pollux/polaris/LIVE/beta/
    - git clear -f
    - git reset --hard origin/beta
    - git pull
    - npm install

baking:
  stage: test
  tags:
    - polestar
  script:
    - echo "Pls send help"
catapulting:
  stage: deploy
  tags:
    - polestar
  script:
    - cd /home/pollux/polaris/LIVE/beta/
    - echo "Did this work idk"
    - pm2 restart Pollux.Premium
    - pm2 restart Pollux.Beta