include:
  - template: Code-Quality.gitlab-ci.yml



before_script:
    
  - echo "Hoping this won't break anything"
  
cooking:
  stage: build
  tags:
    - polestar
  script:
    - cd /home/pollux/polaris/DEV/bot/
    - git reset --hard origin/dev
    - git pull
    - npm install

baking:
  stage: test
  tags:
    - polestar
  script:
    - echo "Pls send help"
catapulting:
  stage: deploy
   tags:
    - polestar
  script:
    - cd /home/pollux/polaris/DEV/bot/
    - echo "Did this work idk"
    - plx-reload polaris