before_script:    
  - echo "Hoping this won't break anything"
  
cooking:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

  tags:
    - polestar
  script:
    - cd /home/pollux/polaris/DEV/bot/
    - git clean -f
    - git reset --hard origin/dev
    - git pull
    - npm install
    - npm install @polestar/i18n

baking:
  stage: test
  tags:
    - polestar
  script:
    - echo "Pls send help"
catapulting:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "beta"
  tags:
    - polestar
  script:
    - cd /home/pollux/polaris/LIVE/beta/
    - echo "Did this work idk"    
    - git clean -f
    - git reset --hard origin/beta
    - git pull
    - npm install
    - npm install @polestar/i18n
    - pm2 restart Pollux.Premium
