module.exports = {
    //POLLUX ORIGINAL
    games: [
        ["+help for commands",3]
        ,["@ me for help",3]
        ,["+status for bot info",0]
        ,["+invite Invite me to your server!",1]
        ,["Check the most beautiful profile ever with p!profile",3]
        ,["Setup your Profile at pollux.gg/dash",2]
        ,["See commands at pollux.gg/commands",1]
        ,["Neverwinter Nights",0]
        ,["Warcraft III",0]
        ,["www.pollux.gg",3]
        ,["Check our subreddit! /r/Pollux",3]
        ,["@maidPollux | Follow me on Twitter~",3]
        ,["Play Blackjack with me! (+bjk)",1]
        ,["@ me for help",3]
        ,["Play Slots and get some Rubines! (+slots)",1]
        ,["Gather your friends for a roulette game! (+roulette)",1]
        ,["Heroes of the Storm",0]
        ,["The Witcher 3",0]
        ,["otacos na fogueira",0]
        ,["Fatal Frame",0] 
        ,["Hyperdimension Neptunia",0]
        ,["Guild Wars 2",0]
        ,["EarthBound",0]
        ,["Elsword",0]
        ,["Ace Combat",0]
        ,["Mahjong",0]
        ,["Starcraft II",0]
        ,["@ me for help",3]
        ,["Technical Death Metal",2]
        ,["Lineage II",0]
        ,["Campo Minado",0]
        ,["Paciência Spider",0]
        ,["Imposto é Roubo!",3]
        ,["Bora Temer",3]
        ,["Sudoku",0]
        ,["DARK SOULS",0]
        ,["dead",0]
        ,["guitar",0]
        ,["the xylophone",0]
        ,["@ me for help",3]
        ,["Yandere Simulator",0]
        ,["Yandere Simulator",0]
        ,["EUROTRUCK Simulator",0]
        ,["Microsoft Solitaire Collection 2018 Exclusive Promo Version Czech Edition",0]
        ,["Faceball 2000",0]
        ,["Akiba's Trip",0]
        ,["Noticing something weird? Contact support!",2]
        ,["Blackjack",0]
        ,["the world BURN",3]
        ,["the USSR National Anthem",2]
        ,["out",3]
        ,["dogs",3]
        ,["Bee Movie",3]
        ,["Lazy Town",3]
        ,["Japanese Jazz Fusion Mixtapes",2]
        ,["Ｖａｐｏｒｗａｖｅ",2]
        ,["Technical Death Metal",2]
        ,["ＭＡＣＩＮＴＯＳＨ　ＰＬＵＳ　－　リサフランク４２０　／　現代のコンピュー",2]
        ,["We are Number One",2]
        ,["Chip music",2]
        ,["your confessions",2]
        ,["@ me for help",3]
    ]


}
