name: Version

on:
  push:
    branches: [ test ]

jobs:
  version:

    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Update Package V
        run: npm version patch -m "Autoupgrade to %s" 
          
