name: Git Version

on:
  push:
    branches: [ dev ]

jobs:
  version:

    runs-on: ubuntu-latest

    steps:
      - name: goto
        run: |
          echo $PWD
          cd ./
          echo $PWD
          

