name: Version

on:
  push:
    branches: [ test ]

jobs:
  version:

    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Update Package V
        run: | 
          git branch
          git config user.email "bot@pollux.gg"
          git config  user.name "Update Bot"
          npm version patch -m "Autoupgrade to %s"
          git push
          
          
