name: Version

on:
  push:
    branches: [ dev ]

jobs:
  version:

    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: goto
        run: |
          echo $PWD
          ls
          
