name: Patch

on:
  push:
    branches: [ dev ]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Update Review
        run: | 
          git config --global user.email "bot@pollux.gg"
          git config --global user.name "Pollux Autoupdate"
          npm version patch -m "Autopatch v to %s"
          git push
