name: Version

on:
  push:
    branches: [ test ]

jobs:

  update-package:
    runs-on: self-hosted
    steps:    
    - name: Update Package Lock
      run: |
        npm install
        git add ./package-lock.json
        git commit -m "Auto update package-lock"      
    
  version:
    runs-on: ubuntu-latest
    steps:      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.5'
          
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Update Package V
        run: | 
          npm version patch -m "Autoupgrade to %s"
          git push
          
          
