name: Version

on:
  push:
    branches: [ test ]

jobs:
  version:

    runs-on: ubuntu-latest

    steps:      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.5'
          
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SPK }}
          
      - name: Set Git Config      
        run: |
          git config user.email "bot@pollux.gg"
          git config  user.name "Update Bot"
      - run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/
      
      - name: Update Package Lock
        run: |
          git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/
          npm install
          git add ./package-lock.json
          git commit -m "Auto update package-lock"          
          
      - name: Update Package V
        run: | 
          npm version patch -m "Autoupgrade to %s"
          git push
          
          
